version: '3.8'

services: 
  app-jenkins:
    container_name: app_jenkins
    build: 
      context: jenkins/.
    volumes: 
      - jenkins_home:/var/jenkins_home
      - jenkins_logs:/var/log/jenkins
    ports: 
      - "8080:8080"
    environment: 
      JENKINS_OPTS: '--handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log  --webroot=/var/cache/jenkins/war'
      JAVA_OPTS: '-Xmx8192m'

volumes:
  jenkins_home: 
  jenkins_logs: 