version: '3.8'

services: 
  app-jenkins-master:
    container_name: app_jenkins_master
    build: ./jenkins-master
    volumes: 
      - jenkins_home:/var/jenkins_home
      - jenkins_logs:/var/log/jenkins
    ports: 
      - "50000:50000"
    networks:
      - jenkins-net
    environment: 
      JENKINS_OPTS: '--handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log  --webroot=/var/cache/jenkins/war'
      JAVA_OPTS: '-Xmx8192m'
  
  dns-jenkins-nginx:
    build: ./jenkins-nginx/.
    container_name: dns_jenkins_nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net

volumes:
  jenkins_home: 
  jenkins_logs: 

networks: 
  jenkins-net:
    driver: bridge